#!/bin/bash
NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyDaJOGyePB9Q_7M8PVHz-WZbAawtDp6KYg"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="punx-subscription-management.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_DATABASE_URL="https://punx-subscription-management-default-rtdb.firebaseio.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="punx-subscription-management"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="punx-subscription-management.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="390232201458"
NEXT_PUBLIC_FIREBASE_APP_ID="1:390232201458:web:c491a6c2f51406133a186b"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-SXGTQSPLYM"

# Recreate .env.local
cat << ENV_EOF > .env.local
NEXT_PUBLIC_FIREBASE_API_KEY="$NEXT_PUBLIC_FIREBASE_API_KEY"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
NEXT_PUBLIC_FIREBASE_DATABASE_URL="$NEXT_PUBLIC_FIREBASE_DATABASE_URL"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
NEXT_PUBLIC_FIREBASE_APP_ID="$NEXT_PUBLIC_FIREBASE_APP_ID"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
ENV_EOF

# Push to Vercel
for env in "production" "preview" "development"; do
  echo "$NEXT_PUBLIC_FIREBASE_API_KEY" | npx vercel env add NEXT_PUBLIC_FIREBASE_API_KEY $env
  echo "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" | npx vercel env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN $env
  echo "$NEXT_PUBLIC_FIREBASE_DATABASE_URL" | npx vercel env add NEXT_PUBLIC_FIREBASE_DATABASE_URL $env
  echo "$NEXT_PUBLIC_FIREBASE_PROJECT_ID" | npx vercel env add NEXT_PUBLIC_FIREBASE_PROJECT_ID $env
  echo "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" | npx vercel env add NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET $env
  echo "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" | npx vercel env add NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID $env
  echo "$NEXT_PUBLIC_FIREBASE_APP_ID" | npx vercel env add NEXT_PUBLIC_FIREBASE_APP_ID $env
  echo "$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID" | npx vercel env add NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID $env
done

# Run deployment
npx vercel --prod --yes
